# Generated by Django 4.1.2 on 2023-01-27 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "episodes",
            "0005_remove_tournamentround_round-unique-tournament-challonge_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="episode",
            name="pass_requirement_out_of",
        ),
        migrations.RemoveField(
            model_name="episode",
            name="pass_requirement_win",
        ),
    ]
