# Generated by Django 4.1.2 on 2023-01-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="challonge_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
