# Generated by Django 4.1.2 on 2023-01-17 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compete", "0005_matchparticipant_challonge_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="challonge_id",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
